export type IconName =
  | 'Activity'
  | 'Airplay'
  | 'AlertCircle'
  | 'AlertOctagon'
  | 'AlertTriangle'
  | 'AlignCenter'
  | 'AlignJustify'
  | 'AlignLeft'
  | 'AlignRight'
  | 'Anchor'
  | 'Aperture'
  | 'Archive'
  | 'ArrowDownCircle'
  | 'ArrowDownLeft'
  | 'ArrowDownRight'
  | 'ArrowDown'
  | 'ArrowLeftCircle'
  | 'ArrowLeft'
  | 'ArrowRightCircle'
  | 'ArrowRight'
  | 'ArrowUpCircle'
  | 'ArrowUpLeft'
  | 'ArrowUpRight'
  | 'ArrowUp'
  | 'AtSign'
  | 'Award'
  | 'BarChart2'
  | 'BarChart'
  | 'BatteryCharging'
  | 'Battery'
  | 'BellOff'
  | 'Bell'
  | 'Bluetooth'
  | 'Bold'
  | 'BookOpen'
  | 'Book'
  | 'Bookmark'
  | 'Box'
  | 'Briefcase'
  | 'Calendar'
  | 'CameraOff'
  | 'Camera'
  | 'Cast'
  | 'CheckCircle'
  | 'CheckSquare'
  | 'Check'
  | 'ChevronDown'
  | 'ChevronLeft'
  | 'ChevronRight'
  | 'ChevronUp'
  | 'ChevronsDown'
  | 'ChevronsLeft'
  | 'ChevronsRight'
  | 'ChevronsUp'
  | 'Chrome'
  | 'Circle'
  | 'Clipboard'
  | 'Clock'
  | 'CloudDrizzle'
  | 'CloudLightning'
  | 'CloudOff'
  | 'CloudRain'
  | 'CloudSnow'
  | 'Cloud'
  | 'Code'
  | 'Codepen'
  | 'Codesandbox'
  | 'Coffee'
  | 'Columns'
  | 'Command'
  | 'Compass'
  | 'Copy'
  | 'CornerDownLeft'
  | 'CornerDownRight'
  | 'CornerLeftDown'
  | 'CornerLeftUp'
  | 'CornerRightDown'
  | 'CornerRightUp'
  | 'CornerUpLeft'
  | 'CornerUpRight'
  | 'Cpu'
  | 'CreditCard'
  | 'Crop'
  | 'Crosshair'
  | 'Database'
  | 'Delete'
  | 'Disc'
  | 'DollarSign'
  | 'DownloadCloud'
  | 'Download'
  | 'Droplet'
  | 'Edit2'
  | 'Edit3'
  | 'Edit'
  | 'ExternalLink'
  | 'EyeOff'
  | 'Eye'
  | 'Facebook'
  | 'FastForward'
  | 'Feather'
  | 'Figma'
  | 'FileMinus'
  | 'FilePlus'
  | 'FileText'
  | 'File'
  | 'Film'
  | 'Fingerprint'
  | 'Filter'
  | 'Flag'
  | 'FolderMinus'
  | 'FolderPlus'
  | 'Folder'
  | 'Framer'
  | 'Frown'
  | 'Gift'
  | 'GitBranch'
  | 'GitCommit'
  | 'GitMerge'
  | 'GitPullRequest'
  | 'Github'
  | 'Gitlab'
  | 'Globe'
  | 'Grid'
  | 'HardDrive'
  | 'Hash'
  | 'Headphones'
  | 'Heart'
  | 'HelpCircle'
  | 'Hexagon'
  | 'Home'
  | 'Image'
  | 'Inbox'
  | 'Info'
  | 'Instagram'
  | 'Italic'
  | 'Key'
  | 'Layers'
  | 'Layout'
  | 'LifeBuoy'
  | 'Link2'
  | 'Link'
  | 'Linkedin'
  | 'List'
  | 'Loader'
  | 'Lock'
  | 'LogIn'
  | 'LogOut'
  | 'Mail'
  | 'MapPin'
  | 'Map'
  | 'Maximize2'
  | 'Maximize'
  | 'Meh'
  | 'Menu'
  | 'MessageCircle'
  | 'MessageSquare'
  | 'MicOff'
  | 'Mic'
  | 'Minimize2'
  | 'Minimize'
  | 'MinusCircle'
  | 'MinusSquare'
  | 'Minus'
  | 'Monitor'
  | 'Moon'
  | 'MoreHorizontal'
  | 'MoreVertical'
  | 'MousePointer'
  | 'Move'
  | 'Music'
  | 'Navigation2'
  | 'Navigation'
  | 'Octagon'
  | 'Package'
  | 'Paperclip'
  | 'PauseCircle'
  | 'Pause'
  | 'PenTool'
  | 'Percent'
  | 'PhoneCall'
  | 'PhoneForwarded'
  | 'PhoneIncoming'
  | 'PhoneMissed'
  | 'PhoneOff'
  | 'PhoneOutgoing'
  | 'Phone'
  | 'PieChart'
  | 'PlayCircle'
  | 'Play'
  | 'PlusCircle'
  | 'PlusSquare'
  | 'Plus'
  | 'Pocket'
  | 'Power'
  | 'Printer'
  | 'Radio'
  | 'RefreshCcw'
  | 'RefreshCw'
  | 'Repeat'
  | 'Rewind'
  | 'RotateCcw'
  | 'RotateCw'
  | 'Rss'
  | 'Save'
  | 'Scissors'
  | 'Search'
  | 'Send'
  | 'Server'
  | 'Settings'
  | 'Share2'
  | 'Share'
  | 'ShieldOff'
  | 'Shield'
  | 'ShoppingBag'
  | 'ShoppingCart'
  | 'Shuffle'
  | 'Sidebar'
  | 'SkipBack'
  | 'SkipForward'
  | 'Slack'
  | 'Slash'
  | 'Sliders'
  | 'Smartphone'
  | 'Smile'
  | 'SortAscending'
  | 'SortDescending'
  | 'Speaker'
  | 'Square'
  | 'Star'
  | 'StopCircle'
  | 'Sun'
  | 'Sunrise'
  | 'Sunset'
  | 'Tablet'
  | 'Tag'
  | 'Target'
  | 'Terminal'
  | 'Thermometer'
  | 'ThumbsDown'
  | 'ThumbsUp'
  | 'ToggleLeft'
  | 'ToggleRight'
  | 'Tool'
  | 'Trash2'
  | 'Trash'
  | 'Trello'
  | 'TrendingDown'
  | 'TrendingUp'
  | 'Triangle'
  | 'Truck'
  | 'Tv'
  | 'Twitch'
  | 'Twitter'
  | 'Type'
  | 'Umbrella'
  | 'Underline'
  | 'Unlock'
  | 'UploadCloud'
  | 'Upload'
  | 'UserCheck'
  | 'UserMinus'
  | 'UserPlus'
  | 'UserX'
  | 'User'
  | 'Users'
  | 'VideoOff'
  | 'Video'
  | 'Voicemail'
  | 'Volume1'
  | 'Volume2'
  | 'VolumeX'
  | 'Volume'
  | 'Watch'
  | 'WifiOff'
  | 'Wifi'
  | 'Wind'
  | 'XCircle'
  | 'XOctagon'
  | 'XSquare'
  | 'X'
  | 'Youtube'
  | 'ZapOff'
  | 'Zap'
  | 'ZoomIn'
  | 'ZoomOut'

export { default as Activity } from './components/Activity'
export { default as Airplay } from './components/Airplay'
export { default as AlertCircle } from './components/AlertCircle'
export { default as AlertOctagon } from './components/AlertOctagon'
export { default as AlertTriangle } from './components/AlertTriangle'
export { default as AlignCenter } from './components/AlignCenter'
export { default as AlignJustify } from './components/AlignJustify'
export { default as AlignLeft } from './components/AlignLeft'
export { default as AlignRight } from './components/AlignRight'
export { default as Anchor } from './components/Anchor'
export { default as Aperture } from './components/Aperture'
export { default as Archive } from './components/Archive'
export { default as ArrowDownCircle } from './components/ArrowDownCircle'
export { default as ArrowDownLeft } from './components/ArrowDownLeft'
export { default as ArrowDownRight } from './components/ArrowDownRight'
export { default as ArrowDown } from './components/ArrowDown'
export { default as ArrowLeftCircle } from './components/ArrowLeftCircle'
export { default as ArrowLeft } from './components/ArrowLeft'
export { default as ArrowRightCircle } from './components/ArrowRightCircle'
export { default as ArrowRight } from './components/ArrowRight'
export { default as ArrowUpCircle } from './components/ArrowUpCircle'
export { default as ArrowUpLeft } from './components/ArrowUpLeft'
export { default as ArrowUpRight } from './components/ArrowUpRight'
export { default as ArrowUp } from './components/ArrowUp'
export { default as AtSign } from './components/AtSign'
export { default as Award } from './components/Award'
export { default as BarChart2 } from './components/BarChart2'
export { default as BarChart } from './components/BarChart'
export { default as BatteryCharging } from './components/BatteryCharging'
export { default as Battery } from './components/Battery'
export { default as BellOff } from './components/BellOff'
export { default as Bell } from './components/Bell'
export { default as Bluetooth } from './components/Bluetooth'
export { default as Bold } from './components/Bold'
export { default as BookOpen } from './components/BookOpen'
export { default as Book } from './components/Book'
export { default as Bookmark } from './components/Bookmark'
export { default as Box } from './components/Box'
export { default as Briefcase } from './components/Briefcase'
export { default as Calendar } from './components/Calendar'
export { default as CameraOff } from './components/CameraOff'
export { default as Camera } from './components/Camera'
export { default as Cast } from './components/Cast'
export { default as CheckCircle } from './components/CheckCircle'
export { default as CheckSquare } from './components/CheckSquare'
export { default as Check } from './components/Check'
export { default as ChevronDown } from './components/ChevronDown'
export { default as ChevronLeft } from './components/ChevronLeft'
export { default as ChevronRight } from './components/ChevronRight'
export { default as ChevronUp } from './components/ChevronUp'
export { default as ChevronsDown } from './components/ChevronsDown'
export { default as ChevronsLeft } from './components/ChevronsLeft'
export { default as ChevronsRight } from './components/ChevronsRight'
export { default as ChevronsUp } from './components/ChevronsUp'
export { default as Chrome } from './components/Chrome'
export { default as Circle } from './components/Circle'
export { default as Clipboard } from './components/Clipboard'
export { default as Clock } from './components/Clock'
export { default as CloudDrizzle } from './components/CloudDrizzle'
export { default as CloudLightning } from './components/CloudLightning'
export { default as CloudOff } from './components/CloudOff'
export { default as CloudRain } from './components/CloudRain'
export { default as CloudSnow } from './components/CloudSnow'
export { default as Cloud } from './components/Cloud'
export { default as Code } from './components/Code'
export { default as Codepen } from './components/Codepen'
export { default as Codesandbox } from './components/Codesandbox'
export { default as Coffee } from './components/Coffee'
export { default as Columns } from './components/Columns'
export { default as Command } from './components/Command'
export { default as Compass } from './components/Compass'
export { default as Copy } from './components/Copy'
export { default as CornerDownLeft } from './components/CornerDownLeft'
export { default as CornerDownRight } from './components/CornerDownRight'
export { default as CornerLeftDown } from './components/CornerLeftDown'
export { default as CornerLeftUp } from './components/CornerLeftUp'
export { default as CornerRightDown } from './components/CornerRightDown'
export { default as CornerRightUp } from './components/CornerRightUp'
export { default as CornerUpLeft } from './components/CornerUpLeft'
export { default as CornerUpRight } from './components/CornerUpRight'
export { default as Cpu } from './components/Cpu'
export { default as CreditCard } from './components/CreditCard'
export { default as Crop } from './components/Crop'
export { default as Crosshair } from './components/Crosshair'
export { default as Database } from './components/Database'
export { default as Delete } from './components/Delete'
export { default as Disc } from './components/Disc'
export { default as DollarSign } from './components/DollarSign'
export { default as DownloadCloud } from './components/DownloadCloud'
export { default as Download } from './components/Download'
export { default as Droplet } from './components/Droplet'
export { default as Edit2 } from './components/Edit2'
export { default as Edit3 } from './components/Edit3'
export { default as Edit } from './components/Edit'
export { default as ExternalLink } from './components/ExternalLink'
export { default as EyeOff } from './components/EyeOff'
export { default as Eye } from './components/Eye'
export { default as Facebook } from './components/Facebook'
export { default as FastForward } from './components/FastForward'
export { default as Feather } from './components/Feather'
export { default as Figma } from './components/Figma'
export { default as FileMinus } from './components/FileMinus'
export { default as FilePlus } from './components/FilePlus'
export { default as FileText } from './components/FileText'
export { default as File } from './components/File'
export { default as Film } from './components/Film'
export { default as Filter } from './components/Filter'
export { default as Fingerprint } from './components/Fingerprint'
export { default as Flag } from './components/Flag'
export { default as FolderMinus } from './components/FolderMinus'
export { default as FolderPlus } from './components/FolderPlus'
export { default as Folder } from './components/Folder'
export { default as Framer } from './components/Framer'
export { default as Frown } from './components/Frown'
export { default as Gift } from './components/Gift'
export { default as GitBranch } from './components/GitBranch'
export { default as GitCommit } from './components/GitCommit'
export { default as GitMerge } from './components/GitMerge'
export { default as GitPullRequest } from './components/GitPullRequest'
export { default as Github } from './components/Github'
export { default as Gitlab } from './components/Gitlab'
export { default as Globe } from './components/Globe'
export { default as Grid } from './components/Grid'
export { default as HardDrive } from './components/HardDrive'
export { default as Hash } from './components/Hash'
export { default as Headphones } from './components/Headphones'
export { default as Heart } from './components/Heart'
export { default as HelpCircle } from './components/HelpCircle'
export { default as Hexagon } from './components/Hexagon'
export { default as Home } from './components/Home'
export { default as Image } from './components/Image'
export { default as Inbox } from './components/Inbox'
export { default as Info } from './components/Info'
export { default as Instagram } from './components/Instagram'
export { default as Italic } from './components/Italic'
export { default as Key } from './components/Key'
export { default as Layers } from './components/Layers'
export { default as Layout } from './components/Layout'
export { default as LifeBuoy } from './components/LifeBuoy'
export { default as Link2 } from './components/Link2'
export { default as Link } from './components/Link'
export { default as Linkedin } from './components/Linkedin'
export { default as List } from './components/List'
export { default as Loader } from './components/Loader'
export { default as Lock } from './components/Lock'
export { default as LogIn } from './components/LogIn'
export { default as LogOut } from './components/LogOut'
export { default as Mail } from './components/Mail'
export { default as MapPin } from './components/MapPin'
export { default as Map } from './components/Map'
export { default as Maximize2 } from './components/Maximize2'
export { default as Maximize } from './components/Maximize'
export { default as Meh } from './components/Meh'
export { default as Menu } from './components/Menu'
export { default as MessageCircle } from './components/MessageCircle'
export { default as MessageSquare } from './components/MessageSquare'
export { default as MicOff } from './components/MicOff'
export { default as Mic } from './components/Mic'
export { default as Minimize2 } from './components/Minimize2'
export { default as Minimize } from './components/Minimize'
export { default as MinusCircle } from './components/MinusCircle'
export { default as MinusSquare } from './components/MinusSquare'
export { default as Minus } from './components/Minus'
export { default as Monitor } from './components/Monitor'
export { default as Moon } from './components/Moon'
export { default as MoreHorizontal } from './components/MoreHorizontal'
export { default as MoreVertical } from './components/MoreVertical'
export { default as MousePointer } from './components/MousePointer'
export { default as Move } from './components/Move'
export { default as Music } from './components/Music'
export { default as Navigation2 } from './components/Navigation2'
export { default as Navigation } from './components/Navigation'
export { default as Octagon } from './components/Octagon'
export { default as Package } from './components/Package'
export { default as Paperclip } from './components/Paperclip'
export { default as PauseCircle } from './components/PauseCircle'
export { default as Pause } from './components/Pause'
export { default as PenTool } from './components/PenTool'
export { default as Percent } from './components/Percent'
export { default as PhoneCall } from './components/PhoneCall'
export { default as PhoneForwarded } from './components/PhoneForwarded'
export { default as PhoneIncoming } from './components/PhoneIncoming'
export { default as PhoneMissed } from './components/PhoneMissed'
export { default as PhoneOff } from './components/PhoneOff'
export { default as PhoneOutgoing } from './components/PhoneOutgoing'
export { default as Phone } from './components/Phone'
export { default as PieChart } from './components/PieChart'
export { default as PlayCircle } from './components/PlayCircle'
export { default as Play } from './components/Play'
export { default as PlusCircle } from './components/PlusCircle'
export { default as PlusSquare } from './components/PlusSquare'
export { default as Plus } from './components/Plus'
export { default as Pocket } from './components/Pocket'
export { default as Power } from './components/Power'
export { default as Printer } from './components/Printer'
export { default as Radio } from './components/Radio'
export { default as RefreshCcw } from './components/RefreshCcw'
export { default as RefreshCw } from './components/RefreshCw'
export { default as Repeat } from './components/Repeat'
export { default as Rewind } from './components/Rewind'
export { default as RotateCcw } from './components/RotateCcw'
export { default as RotateCw } from './components/RotateCw'
export { default as Rss } from './components/Rss'
export { default as Save } from './components/Save'
export { default as Scissors } from './components/Scissors'
export { default as Search } from './components/Search'
export { default as Send } from './components/Send'
export { default as Server } from './components/Server'
export { default as Settings } from './components/Settings'
export { default as Share2 } from './components/Share2'
export { default as Share } from './components/Share'
export { default as ShieldOff } from './components/ShieldOff'
export { default as Shield } from './components/Shield'
export { default as ShoppingBag } from './components/ShoppingBag'
export { default as ShoppingCart } from './components/ShoppingCart'
export { default as Shuffle } from './components/Shuffle'
export { default as Sidebar } from './components/Sidebar'
export { default as SkipBack } from './components/SkipBack'
export { default as SkipForward } from './components/SkipForward'
export { default as Slack } from './components/Slack'
export { default as Slash } from './components/Slash'
export { default as Sliders } from './components/Sliders'
export { default as Smartphone } from './components/Smartphone'
export { default as Smile } from './components/Smile'
export { default as SortAscending } from './components/SortAscending'
export { default as SortDescending } from './components/SortDescending'
export { default as Speaker } from './components/Speaker'
export { default as Square } from './components/Square'
export { default as Star } from './components/Star'
export { default as StopCircle } from './components/StopCircle'
export { default as Sun } from './components/Sun'
export { default as Sunrise } from './components/Sunrise'
export { default as Sunset } from './components/Sunset'
export { default as Tablet } from './components/Tablet'
export { default as Tag } from './components/Tag'
export { default as Target } from './components/Target'
export { default as Terminal } from './components/Terminal'
export { default as Thermometer } from './components/Thermometer'
export { default as ThumbsDown } from './components/ThumbsDown'
export { default as ThumbsUp } from './components/ThumbsUp'
export { default as ToggleLeft } from './components/ToggleLeft'
export { default as ToggleRight } from './components/ToggleRight'
export { default as Tool } from './components/Tool'
export { default as Trash2 } from './components/Trash2'
export { default as Trash } from './components/Trash'
export { default as Trello } from './components/Trello'
export { default as TrendingDown } from './components/TrendingDown'
export { default as TrendingUp } from './components/TrendingUp'
export { default as Triangle } from './components/Triangle'
export { default as Truck } from './components/Truck'
export { default as Tv } from './components/Tv'
export { default as Twitch } from './components/Twitch'
export { default as Twitter } from './components/Twitter'
export { default as Type } from './components/Type'
export { default as Umbrella } from './components/Umbrella'
export { default as Underline } from './components/Underline'
export { default as Unlock } from './components/Unlock'
export { default as UploadCloud } from './components/UploadCloud'
export { default as Upload } from './components/Upload'
export { default as UserCheck } from './components/UserCheck'
export { default as UserMinus } from './components/UserMinus'
export { default as UserPlus } from './components/UserPlus'
export { default as UserX } from './components/UserX'
export { default as User } from './components/User'
export { default as Users } from './components/Users'
export { default as VideoOff } from './components/VideoOff'
export { default as Video } from './components/Video'
export { default as Voicemail } from './components/Voicemail'
export { default as Volume1 } from './components/Volume1'
export { default as Volume2 } from './components/Volume2'
export { default as VolumeX } from './components/VolumeX'
export { default as Volume } from './components/Volume'
export { default as Watch } from './components/Watch'
export { default as WifiOff } from './components/WifiOff'
export { default as Wifi } from './components/Wifi'
export { default as Wind } from './components/Wind'
export { default as XCircle } from './components/XCircle'
export { default as XOctagon } from './components/XOctagon'
export { default as XSquare } from './components/XSquare'
export { default as X } from './components/X'
export { default as Youtube } from './components/Youtube'
export { default as ZapOff } from './components/ZapOff'
export { default as Zap } from './components/Zap'
export { default as ZoomIn } from './components/ZoomIn'
export { default as ZoomOut } from './components/ZoomOut'
